<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerApeXifR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerApeXifR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerApeXifR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerApeXifR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerApeXifR\App_KernelDevDebugContainer([
    'container.build_hash' => 'ApeXifR',
    'container.build_id' => '11c47e48',
    'container.build_time' => 1729767276,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerApeXifR');
