<?php

namespace ContainerSJU0x1y;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9XNsBwGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9XNsBwG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9XNsBwG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\GRecrutementsController::apply' => ['privates', '.service_locator.C98KNaG', 'get_ServiceLocator_C98KNaGService', true],
            'App\\Controller\\GRecrutementsController::authorDelete1' => ['privates', '.service_locator.yxANsRR', 'get_ServiceLocator_YxANsRRService', true],
            'App\\Controller\\GRecrutementsController::authorDetails' => ['privates', '.service_locator.q2iM02Z', 'get_ServiceLocator_Q2iM02ZService', true],
            'App\\Controller\\GRecrutementsController::edit' => ['privates', '.service_locator.C98KNaG', 'get_ServiceLocator_C98KNaGService', true],
            'App\\Controller\\GRecrutementsController::recruitmentAdd' => ['privates', '.service_locator.IwuOEF6', 'get_ServiceLocator_IwuOEF6Service', true],
            'App\\Controller\\GRecrutementsController::show_all' => ['privates', '.service_locator.Xw86vfZ', 'get_ServiceLocator_Xw86vfZService', true],
            'App\\Controller\\GRecrutementsController::show_alluser' => ['privates', '.service_locator.Xw86vfZ', 'get_ServiceLocator_Xw86vfZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\GRecrutementsController:apply' => ['privates', '.service_locator.C98KNaG', 'get_ServiceLocator_C98KNaGService', true],
            'App\\Controller\\GRecrutementsController:authorDelete1' => ['privates', '.service_locator.yxANsRR', 'get_ServiceLocator_YxANsRRService', true],
            'App\\Controller\\GRecrutementsController:authorDetails' => ['privates', '.service_locator.q2iM02Z', 'get_ServiceLocator_Q2iM02ZService', true],
            'App\\Controller\\GRecrutementsController:edit' => ['privates', '.service_locator.C98KNaG', 'get_ServiceLocator_C98KNaGService', true],
            'App\\Controller\\GRecrutementsController:recruitmentAdd' => ['privates', '.service_locator.IwuOEF6', 'get_ServiceLocator_IwuOEF6Service', true],
            'App\\Controller\\GRecrutementsController:show_all' => ['privates', '.service_locator.Xw86vfZ', 'get_ServiceLocator_Xw86vfZService', true],
            'App\\Controller\\GRecrutementsController:show_alluser' => ['privates', '.service_locator.Xw86vfZ', 'get_ServiceLocator_Xw86vfZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\GRecrutementsController::apply' => '?',
            'App\\Controller\\GRecrutementsController::authorDelete1' => '?',
            'App\\Controller\\GRecrutementsController::authorDetails' => '?',
            'App\\Controller\\GRecrutementsController::edit' => '?',
            'App\\Controller\\GRecrutementsController::recruitmentAdd' => '?',
            'App\\Controller\\GRecrutementsController::show_all' => '?',
            'App\\Controller\\GRecrutementsController::show_alluser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\GRecrutementsController:apply' => '?',
            'App\\Controller\\GRecrutementsController:authorDelete1' => '?',
            'App\\Controller\\GRecrutementsController:authorDetails' => '?',
            'App\\Controller\\GRecrutementsController:edit' => '?',
            'App\\Controller\\GRecrutementsController:recruitmentAdd' => '?',
            'App\\Controller\\GRecrutementsController:show_all' => '?',
            'App\\Controller\\GRecrutementsController:show_alluser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
