security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Ensure this matches the field you use for authentication (email in this case)

    password_hashers:
        App\Entity\User:
            algorithm: auto  # Auto-detect the best hashing algorithm (bcrypt, argon2i, etc.)

    firewalls:
        main:
            # Form-based authentication
            form_login:
                login_path: app_login       # Route to login form
                check_path: app_login       # Path where login form posts to (the same as login_path)
                username_parameter: email   # Match the 'email' field in the login form
                password_parameter: password # Match the 'password' field in the login form
                enable_csrf: true  # Enable CSRF protection (instead of csrf_token_generator)
                # Remove or comment out default_target_path
                # default_target_path: /  # This can be any fallback route

            # Logout functionality
            logout:
                path: app_logout  # Route to logout
                target: app_login  # Redirect to login page after logout

            # Remember me functionality
            remember_me:
                secret: '%kernel.secret%'  # Should be a unique, secret value (usually from the kernel secret)
                lifetime: 604800  # Remember me cookie lifetime in seconds (1 week)

    access_control:
        # Define any access control rules based on roles here
        # For example:
        - { path: ^/events, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
