<?php

<<<<<<<< HEAD:Project_clubs/var/cache/dev/ContainerPVouLNZ/getDeleteEventControllerService.php
namespace ContainerPVouLNZ;
========
namespace ContainerApeXifR;
>>>>>>>> 0700c0c1e442bf75888e33af3dedb90bb9a908c5:Project_clubs/var/cache/dev/ContainerApeXifR/getDeleteEventControllerService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteEventControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DeleteEventController' shared autowired service.
     *
     * @return \App\Controller\DeleteEventController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'DeleteEventController.php';

        $container->services['App\\Controller\\DeleteEventController'] = $instance = new \App\Controller\DeleteEventController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\DeleteEventController', $container));

        return $instance;
    }
}
