<?php

namespace ContainerLvy6sg1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRessourceRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5.CUrZi.App\Repository\RessourceRepository' shared service.
     *
     * @return \App\Repository\RessourceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5.CUrZi": it references class "App\\Repository\\RessourceRepository" but no such service exists.');
    }
}
