<?php

<<<<<<<< HEAD:var/cache/dev/ContainerWS7VQJj/getClub2Service.php
namespace ContainerWS7VQJj;
========
namespace ContainerNE8LIaj;
>>>>>>>> c833b8a74c735c5e13611c5fa5b159719b6f1d30:var/cache/dev/ContainerNE8LIaj/getClub2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClub2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.eAaJ0X7.App\Entity\Club' shared service.
     *
     * @return \App\Entity\Club
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.eAaJ0X7": it needs an instance of "App\\Entity\\Club" but this type has been excluded in "config/services.yaml".');
    }
}
