<?php

namespace ContainerLx0q1xL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClub4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yHlyP5W.App\Entity\Club' shared service.
     *
     * @return \App\Entity\Club
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yHlyP5W": it needs an instance of "App\\Entity\\Club" but this type has been excluded in "config/services.yaml".');
    }
}
