<?php

namespace ContainerD27QkWd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KoawAmkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.koawAmk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.koawAmk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'parameterBag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'doctrine' => '?',
            'parameterBag' => '?',
        ]);
    }
}
