<?php

namespace ContainerFgAu6GR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClubRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kwKogkx.App\Repository\clubRepository' shared service.
     *
     * @return \App\Repository\clubRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kwKogkx": it references class "App\\Repository\\clubRepository" but no such service exists. Did you mean "App\\Repository\\ClubRepository"?');
    }
}
