<?php

<<<<<<<< HEAD:var/cache/dev/ContainerTLloNGl/getClubService.php
namespace ContainerTLloNGl;
========
namespace ContainerFgAu6GR;

>>>>>>>> 32b1d21577280cb80c1c507b541be4dee7c0bc31:var/cache/dev/ContainerFgAu6GR/getClub3Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClub3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.raUDR8y.App\Entity\Club' shared service.
     *
     * @return \App\Entity\Club
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.raUDR8y": it needs an instance of "App\\Entity\\Club" but this type has been excluded in "config/services.yaml".');
    }
}
