<?php

<<<<<<<< HEAD:var/cache/dev/Container3qZku9y/getRessourceService.php
namespace Container3qZku9y;
========
namespace ContainerFgAu6GR;

>>>>>>>> 32b1d21577280cb80c1c507b541be4dee7c0bc31:var/cache/dev/ContainerFgAu6GR/getRessourceService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRessourceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K7XrrNx.App\Entity\Ressource' shared service.
     *
     * @return \App\Entity\Ressource
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.K7XrrNx": it needs an instance of "App\\Entity\\Ressource" but this type has been excluded in "config/services.yaml".');
    }
}
