<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bloc' => [parent::class, 'bloc', null],
        "\0".parent::class."\0".'club' => [parent::class, 'club', null],
        "\0".parent::class."\0".'datedebut' => [parent::class, 'datedebut', null],
        "\0".parent::class."\0".'datefin' => [parent::class, 'datefin', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'participants' => [parent::class, 'participants', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'bloc' => [parent::class, 'bloc', null],
        'club' => [parent::class, 'club', null],
        'datedebut' => [parent::class, 'datedebut', null],
        'datefin' => [parent::class, 'datefin', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'participants' => [parent::class, 'participants', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
