<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recruitment extends \App\Entity\Recruitment implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'candidatures' => [parent::class, 'candidatures', null],
        "\0".parent::class."\0".'club' => [parent::class, 'club', null],
        "\0".parent::class."\0".'dateCreated' => [parent::class, 'dateCreated', null],
        "\0".parent::class."\0".'dateUpdated' => [parent::class, 'dateUpdated', null],
        "\0".parent::class."\0".'deadline' => [parent::class, 'deadline', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'recruitment' => [parent::class, 'recruitment', null],
        "\0".parent::class."\0".'requirements' => [parent::class, 'requirements', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        'candidatures' => [parent::class, 'candidatures', null],
        'club' => [parent::class, 'club', null],
        'dateCreated' => [parent::class, 'dateCreated', null],
        'dateUpdated' => [parent::class, 'dateUpdated', null],
        'deadline' => [parent::class, 'deadline', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'location' => [parent::class, 'location', null],
        'recruitment' => [parent::class, 'recruitment', null],
        'requirements' => [parent::class, 'requirements', null],
        'status' => [parent::class, 'status', null],
        'title' => [parent::class, 'title', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
