<?php

namespace ContainerHLOhO3Y;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplication2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cKIfloV.App\Entity\Application' shared service.
     *
     * @return \App\Entity\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cKIfloV": it needs an instance of "App\\Entity\\Application" but this type has been excluded in "config/services.yaml".');
    }
}
