<?php

namespace ContainerXwsxPSm;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TFzYaFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tFzYa_f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tFzYa_f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ressourceRepository' => ['privates', '.errored.9Uzv6Y1', NULL, 'Cannot determine controller argument for "App\\Controller\\GRessourcesController::indexxx()": the $ressourceRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\RessourceRepository".'],
        ], [
            'ressourceRepository' => '?',
        ]);
    }
}
