# config/routes.yaml

controllers:
  resource: ../src/Controller/
  type: attribute  # This enables route attributes in your controllers
index:
    path: /
    controller: App\Controller\GusersController::index

