parameters:
  club_logos_directory: "../public/uploads/logos"
  profile_pictures_directory: "../public/uploads/profilePictures"
  cv_directory: '../public/uploads/cv'
  event_pictures_directory: "../public/uploads/events"
  uploads_directory: "../public/uploads/ressources"
  images_directory: '%kernel.project_dir%/public/uploads/images'

services:
  _defaults:
    autowire: true  # Automatically injects dependencies in your services
    autoconfigure: true  # Automatically registers your services as commands, event subscribers, etc.

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Repository\:
    resource: "../src/Repository"
    tags: ["doctrine.repository_service"]
