<?php

namespace ContainerK2o9K6a;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XRqqVGSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xRqqVGS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xRqqVGS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'applicationClubRepository' => ['privates', 'App\\Repository\\ApplicationClubRepository', 'getApplicationClubRepositoryService', true],
            'club' => ['privates', '.errored..service_locator.xRqqVGS.App\\Entity\\Club', NULL, 'Cannot autowire service ".service_locator.xRqqVGS": it needs an instance of "App\\Entity\\Club" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'applicationClubRepository' => 'App\\Repository\\ApplicationClubRepository',
            'club' => 'App\\Entity\\Club',
            'entityManager' => '?',
            'mailer' => '?',
        ]);
    }
}
