<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPp8Sold\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPp8Sold/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPp8Sold.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPp8Sold\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPp8Sold\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pp8Sold',
    'container.build_id' => '4b2bf5b8',
    'container.build_time' => 1730823149,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPp8Sold');
