<?php

<<<<<<<< HEAD:var/cache/dev/Container5bYnsck/get_ServiceLocator_QclnwotService.php
namespace Container5bYnsck;

========
namespace ContainerBg3qXMC;
>>>>>>>> 7b24a4db39587ab85a1972100e28e5aa92097661:var/cache/dev/ContainerBg3qXMC/get_ServiceLocator_QclnwotService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QclnwotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qclnwot' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qclnwot'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'applicationRepository' => ['privates', 'App\\Repository\\ApplicationRepository', 'getApplicationRepositoryService', true],
            'club' => ['privates', '.errored..service_locator.Qclnwot.App\\Entity\\Club', NULL, 'Cannot autowire service ".service_locator.Qclnwot": it needs an instance of "App\\Entity\\Club" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'applicationRepository' => 'App\\Repository\\ApplicationRepository',
            'club' => 'App\\Entity\\Club',
            'entityManager' => '?',
        ]);
    }
}
