<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRJsuRf9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRJsuRf9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRJsuRf9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRJsuRf9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRJsuRf9\App_KernelDevDebugContainer([
    'container.build_hash' => 'RJsuRf9',
    'container.build_id' => '6b21414b',
    'container.build_time' => 1732185729,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRJsuRf9');
