<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrW3W1w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrW3W1w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCrW3W1w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCrW3W1w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCrW3W1w\App_KernelDevDebugContainer([
    'container.build_hash' => 'CrW3W1w',
    'container.build_id' => 'd3c064df',
    'container.build_time' => 1732746043,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrW3W1w');
