<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerCWpOZPY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCWpOZPY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCWpOZPY.legacy');
=======
if (\class_exists(\ContainerLvy6sg1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLvy6sg1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLvy6sg1.legacy');
>>>>>>> aebebaeb0a495688a12233f88f8765dcfbd65d2b

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerCWpOZPY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCWpOZPY\App_KernelDevDebugContainer([
    'container.build_hash' => 'CWpOZPY',
    'container.build_id' => 'ff1c0b30',
    'container.build_time' => 1732730457,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCWpOZPY');
=======
    \class_alias(\ContainerLvy6sg1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLvy6sg1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lvy6sg1',
    'container.build_id' => '3999e16e',
    'container.build_time' => 1732726494,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLvy6sg1');
>>>>>>> aebebaeb0a495688a12233f88f8765dcfbd65d2b
